spring:
  application:
    name: Springboot Test Bench Application



  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop

    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kaktus.test.mail@gmail.com
    password: ewxyavdnriyzjgpi
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
      mail.mime.charset: UTF

  jackson:
    time-zone: Asia/Jakarta

server:
  port: 8000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2.enabled: true

springdoc:
  packages-to-scan: dev.local.springboot_test_bench.controllers
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /documentation
    tagsSorter: alpha
    filter: true

test-bench:
  allowed-client-url: '*'
  restricted-end-point: /test-bench

  swagger-end-point-allowed: /v1/api-docs/swagger-config
  swagger-2-end-point-allowed: /v1/api-docs
  openapi:
    dev-url: 'http://localhost:8000'
    prod-url: 'http://localhost:8000'
  jwt:
    secret-key: 3C4D23308E634699030B1578831D7F3DF7A230289D13FD03D896280FB0D7D765
    expiration: 24 #in hours
    refresh.expiration: 600000

management:
  endpoints:
    web:
      exposure.include: '*'
      base-path: /monitoring
      base-path-mapping.health: healthcheck

  endpoint:
    health:
      show-details: ALWAYS
      group.health-group.include: ping, diskSpace
    prometheus: true

  info.env.enabled: true

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java.version: @java.version@

  build-timestamp: @maven.build.timestamp@